---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Reload alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: reloaded

- name: Validate alertmanager config
  ansible.builtin.command:
    cmd: /usr/local/bin/amtool check-config /etc/alertmanager/alertmanager.yml
  changed_when: false
