---
galaxy_info:
  author: homelab
  description: Deploy Jellyfin media streaming server
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy

dependencies: []
