---
- name: Restart container for TUN device
  community.proxmox.proxmox:
    api_host: "{{ proxmox_config[proxmox_node | default(proxmox_default_node)].host }}"
    api_user: "{{ proxmox_config[proxmox_node | default(proxmox_default_node)].user }}"
    api_token_id: "{{ _api_token_name }}"
    api_token_secret: "{{ proxmox_config[proxmox_node | default(proxmox_default_node)].api_token_secret }}"
    validate_certs: "{{ proxmox_config[proxmox_node | default(proxmox_default_node)].validate_certs }}"
    vmid: "{{ container_vmid }}"
    node: "{{ proxmox_config[proxmox_node | default(proxmox_default_node)].node }}"
    state: restarted
  delegate_to: localhost
  become: false
