---
all:
  children:
    k3s_cluster:
      children:
        server:
          hosts:
            k3s-01:
              ansible_host: 192.168.0.111
              ansible_user: pbs
        agent:
          hosts:
            k3s-02:
              ansible_host: 192.168.0.112
              ansible_user: pbs
            k3s-03:
              ansible_host: 192.168.0.113
              ansible_user: pbs
            k3s-04:
              ansible_host: 192.168.0.114
              ansible_user: pbs
