---
galaxy_info:
  author: homelab
  description: Deploy bazarr service
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy

dependencies:
  - role: homelab.common.container_base
    when: bazarr_apply_container_base | default(false)
