---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Reload prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Validate prometheus config
  ansible.builtin.command:
    cmd: /usr/local/bin/promtool check config /etc/prometheus/prometheus.yml
  changed_when: false
