---
- name: Restart LXC container to apply bind mounts
  ansible.builtin.command:
    cmd: pct reboot {{ container_id }}
  delegate_to: "{{ proxmox_config[nas_proxmox_node].host }}"
  become: true
  vars:
    ansible_user: ansible
  changed_when: true
  listen: Restart LXC container

- name: Wait for container SSH after restart
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 120
  listen: Restart LXC container
