---
- name: Configure unattended-upgrades for Pi
  ansible.builtin.template:
    src: 50unattended-upgrades-pi.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    owner: root
    group: root

- name: Configure automatic updates for Pi
  ansible.builtin.template:
    src: 20auto-upgrades-pi.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    owner: root
    group: root

- name: Enable unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
