---
# Secure Enclave Handlers

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart wireguard enclave
  ansible.builtin.systemd:
    name: wg-quick@wg-enclave
    state: restarted
  failed_when: false

- name: Restart enclave dashboard
  ansible.builtin.systemd:
    name: enclave-dashboard
    state: restarted
  failed_when: false
