---
# Secure Enclave Handlers

- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
