---
# Unbound handlers

- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
  listen: Restart unbound

- name: Reload unbound
  ansible.builtin.systemd:
    name: unbound
    state: reloaded
  listen: Reload unbound

- name: Validate unbound config
  ansible.builtin.command: unbound-checkconf
  listen: Validate unbound config
  changed_when: false
