---
jellyfin_version: "latest"
jellyfin_port: 8096
jellyfin_https_port: 8920
jellyfin_container_name: "jellyfin"
jellyfin_puid: 1000
jellyfin_pgid: 1000
jellyfin_timezone: "UTC"
jellyfin_config_dir: /opt/jellyfin/config
jellyfin_data_dir: /opt/jellyfin
jellyfin_cache_dir: /opt/jellyfin/cache
jellyfin_media_dir: "/media"
jellyfin_docker_image: "jellyfin/jellyfin"
jellyfin_docker_restart_policy: "unless-stopped"
jellyfin_memory_limit: "2g"
jellyfin_configure_firewall: true

# Hardware acceleration (Intel QSV, VAAPI)
jellyfin_hardware_acceleration: false
jellyfin_gpu_device: "/dev/dri/renderD128"

jellyfin_extra_volumes: []
