---
prowlarr_version: "latest"
prowlarr_port: 9696
prowlarr_container_name: "prowlarr"
prowlarr_puid: 1000
prowlarr_pgid: 1000
prowlarr_timezone: "UTC"
prowlarr_config_dir: /opt/prowlarr/config
prowlarr_data_dir: /opt/prowlarr
prowlarr_docker_image: "lscr.io/linuxserver/prowlarr"
prowlarr_docker_restart_policy: "unless-stopped"
prowlarr_memory_limit: "512m"
prowlarr_configure_firewall: true
