---
# WireGuard handlers

- name: Check WireGuard service status
  ansible.builtin.systemd:
    name: wg-quick@wg0
  register: wireguard_service_status
  listen: Restart wireguard
  changed_when: false

- name: Restart wireguard if running
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted
  listen: Restart wireguard
  when: wireguard_service_status.status.ActiveState == 'active'

- name: Start wireguard if not running
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: started
    enabled: true
  listen: Restart wireguard
  when: wireguard_service_status.status.ActiveState != 'active'

- name: Reload wireguard
  ansible.builtin.shell: |
    set -o pipefail
    wg syncconf wg0 <(wg-quick strip wg0)
  args:
    executable: /bin/bash
  listen: Reload wireguard
  changed_when: false
