---
bazarr_version: "latest"
bazarr_port: 6767
bazarr_container_name: "bazarr"
bazarr_puid: 1000
bazarr_pgid: 1000
bazarr_timezone: "UTC"
bazarr_config_dir: /opt/bazarr/config
bazarr_data_dir: /opt/bazarr
bazarr_media_dir: "/media"
bazarr_docker_image: "lscr.io/linuxserver/bazarr"
bazarr_docker_restart_policy: "unless-stopped"
bazarr_memory_limit: "512m"
bazarr_configure_firewall: true
bazarr_extra_volumes: []
