---
# Common setup handlers

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
