---
- name: Restart ssh
  systemd:
    name: ssh
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
