---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart pve-exporter
  ansible.builtin.systemd:
    name: pve-exporter
    state: restarted

- name: Restart pve-exporter container
  community.docker.docker_container:
    name: pve-exporter
    state: started
    restart: true
  when: pve_exporter_use_docker | default(false)
