---
# AlertManager default variables
alertmanager_version: "0.27.0"
alertmanager_port: 9093
alertmanager_config_dir: /etc/alertmanager
alertmanager_data_dir: /var/lib/alertmanager
alertmanager_user: alertmanager
alertmanager_group: alertmanager
