---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart openwrt
  systemd:
    name: openwrt
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted