---
- name: Destroy test LXC container on Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: 192.168.0.56
    proxmox_user: root@pam
    proxmox_node: pve-mac

  tasks:
    - name: Stop the test container
      community.proxmox.proxmox:
        vmid: 250
        node: {{ proxmox_node }}
        api_user: {{ proxmox_user }}
        api_password: {{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: {{ proxmox_host }}
        state: stopped
        force: true
      ignore_errors: true

    - name: Remove the test container
      community.proxmox.proxmox:
        vmid: 250
        node: {{ proxmox_node }}
        api_user: {{ proxmox_user }}
        api_password: {{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: {{ proxmox_host }}
        state: absent
      ignore_errors: true
